### ISSUE TITLE
Switch Endpoint

### ISSUE THREAD

**Issue by SirLouen** [AndreVarandas/clash-royale-api#97]
It would be great to have a way to switch endpoint using RoyaleAPI Proxy instead of the official endpoint specially when working under development environment https://docs.royaleapi.com/proxy.html

In https://github.com/AndreVarandas/clash-royale-api/blob/0c969313fc8437628bbcfa87f27e9008605e3b8d/src/constants/index.ts

**Comment by AndreVarandas** [comment]
Hi, thank you for your valuable suggestion. This was implemented with version [2.1.0](https://github.com/AndreVarandas/clash-royale-api/releases/tag/v2.1.0).

You now use it like this:

```typescript
const api = new ClashRoyaleAPI(
  'the token you got from the api',
  'https://proxy.royaleapi.dev/v1',
)
```

I'm now closing the issue but please feel free to re-open it if something is missing.
